# Generated by Django 4.2.1 on 2023-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accesstoken',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idtoken',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
