"""
Django settings for app7 project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9vy=vas*5_v0++5u#q#d43$ibynigj$*j#!$&+@ffeenn#@zp_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['app7.dev.sonia.de']

# OIDC Settings
OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://id.dev.sonia.de/realms/dev/protocol/openid-connect/auth'
OIDC_OP_TOKEN_ENDPOINT = 'https://id.dev.sonia.de/realms/dev/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = 'https://id.dev.sonia.de/realms/dev/protocol/openid-connect/userinfo'
OIDC_OP_JWKS_ENDPOINT = 'https://id.dev.sonia.de/realms/dev/protocol/openid-connect/certs'
OIDC_OP_ISSUER_ENDPOINT = 'https://id.dev.sonia.de/realms/dev'

OIDC_RP_CLIENT_ID = 'app7'
OIDC_RP_CLIENT_SECRET = 'FSRSKzkjiMtRNfOc9pdDaKOY9Hzt0Ond'
OIDC_RP_SCOPES = 'openid email profile phone roles'
OIDC_RP_SIGN_ALGO = 'RS256'

OIDC_VERIFY_SSL = False

LOGIN_URL = '/oidc/authenticate/'
LOGIN_REDIRECT_URL = 'http://app7.dev.sonia.de:8087/protected'
LOGOUT_REDIRECT_URL = 'https://id.dev.sonia.de/realms/dev/protocol/openid-connect/logout?post_logout_redirect_uri=http://app7.dev.sonia.de:8087&client_id=app7'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'mozilla_django_oidc',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_app7',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'authentication_backends.sonia_oidc.SoniaOIDC'
)

ROOT_URLCONF = 'app7.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app7.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
