services:
  app1-py:
    build: .
    container_name: app1_py
    hostname: app1.dev.sonia.de
    ports:
      - "8081:8081"
    volumes:
      - .:/work
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - PIP_DISABLE_PIP_VERSION_CHECK=1
    networks:
      - iddev

  app1-redis:
    image: redis:alpine
    hostname: app1-redis
    ports:
      - "6379:6379"
    networks:
      - iddev

networks:
  iddev:
    external: true
