spring:
  application:
    name: l9g-webapp-native-oidc
  profiles:
    active: default
  config:
    import: optional:file:config.yaml
  messages:
    basename: messages
    encoding: UTF-8

logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger:%line - %yellow(%msg %n)"
  level:
    root: INFO
    l9g: TRACE

server:
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: 9h


oidc:
  discovery-uri: https://id.dev.sonia.de/realms/dev/.well-known/openid-configuration

oauth2:
  redirect-uri: http://app1.dev.sonia.de:8081/oidc-login
  post-logout-redirect-uri: http://app1.dev.sonia.de:8081/oidc-logout
  client:
    id: app1
    secret: x45mpvfzvPU5utH7MvNclj2vtilaXW0i
    scope: openid profile email roles
    userid: preferred_username
