#!/bin/bash

# disable filename globbing
set -f

echo "Content-type: text/html; charset=UTF-8"
echo

cat <<EOT
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Userinfo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  </head>
  <body>
    <div class='container' style='margin-top: 2em'>
    <h1>OPAC Userinfo</h1>
    <table class="table table-striped">
      <tbody>
        <tr><th>UID</th><td>$OIDC_CLAIM_preferred_username</td></tr>
        <tr><th>Name</th><td>$OIDC_CLAIM_name</td></tr>
        <tr><th>E-Mail</th><td>$OIDC_CLAIM_email</td></tr>
        <tr><th>Nachname</th><td>$OIDC_CLAIM_family_name</td></tr>
        <tr><th>Vorname</th><td>$OIDC_CLAIM_given_name</td></tr>
        <tr><th>Phonenumber</th><td>$OIDC_CLAIM_phone_number</td></tr>
      </tbody>
    </table>

    <p>
      <a href="/protected?logout=http://app4.dev.sonia.de:8084?iss=$OIDC_CLAIM_iss" class="btn btn-primary btn-lg" role="button">Logout</a>
      <a href="/protected/cgi-bin/test-cgi" class="btn btn-secondary btn-lg" role="button">OIDC Claims</a>
    </p>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>
EOT
